DELETE  {{host}}/api/blogs/64c1b65e4bc508eadf411ad2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1pc3R5IFJpY2t5IiwiaWQiOiI2NGMxNjMyNmU1ZDk0NGQzZDc0ODM4MWEiLCJpYXQiOjE2OTA0MTU0NjMsImV4cCI6MTY5MDQxOTA2M30.9Sy4umAKhm56KU7jFBXjWOxfRtlt3Xtq8LCmIeXcytU
